### ISSUE TITLE
Kite plugin inserting random characters

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#193] opened 2019-07-31 23:19 UTC
User feedback:

> I'm trying to use kite with vim, however it introduces errors when I type quickly (eg just now I typed 'append' and 'appeend' was inserted, or when I typed 'os.path.join', 'os.p ath.join' was inserted). Is this a known bug/is there a fix? Unfortunately, Kite is unusable for me unless this is fixed.

This behavior still persists even after running

```
set completeopt-=longest 
set completeopt+=noinsert 
```

**Comment by georgelroberts** [comment] 2019-08-01 09:22
Hi, thanks for logging the bug for me.

Just to clarify, I am running vim inside tmux.

My vimrc is (sorry it's a bit messy):

```
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'

""code folding
Plugin 'kalekundert/vim-coiled-snake'

Plugin 'ErichDonGubler/vim-sublime-monokai'

Plugin 'vim-airline/vim-airline'

Plugin 'ntpeters/vim-better-whitespace'

Plugin 'skywind3000/asyncrun.vim'

Plugin 'christoomey/vim-tmux-navigator'

Plugin 'ludovicchabant/vim-gutentags'

Plugin 'majutsushi/tagbar'

Plugin 'Yggdroot/indentLine'

Plugin 'tomtom/tcomment_vim'

Plugin 'mbbill/undotree'

Plugin 'vim-python/python-syntax'

Plugin 'elzr/vim-json'

call vundle#end()

filetype plugin indent on 

" Syntax highlighting
let g:python_highlight_all = 1

let g:kite_tab_complete=1
set completeopt+=menu
set completeopt+=noinsert
set completeopt-=menuone
set completeopt-=preview
set completeopt-=longest
" let g:KiteHidePopularPatterns=1
" autocmd CompleteDone * if !pumvisible() | pclose | endif

set cursorline
set hlsearch
set incsearch
" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree
map <C-n> :NERDTreeToggle<CR>

" Quick run via <F5>
nnoremap <F5> :call <SID>compile_and_run()<CR>
let g:asyncrun_mode=0
function! s:compile_and_run()
    exec 'w'
    if &filetype == 'python'
       exec "AsyncRun! time python %"
    endif
endfunction

nnoremap <F6> :call <SID>stop_async()<CR>
function! s:stop_async()
    exec "AsyncStop!"
endfunction

" let g:asyncrun_open = 15
" Press f9 to open quickfix
:noremap <F9> :call asyncrun#quickfix_toggle(8)<cr>

" Remap tagbar
nmap <F4> :TagbarToggle<CR>
let g:tagbar_sort = -1
let g:tagbar_autofocus = 1
let g:tagbar_autoclose = 0
let g:tagbar_compact = 1
let g:tagbar_show_linenumbers = 0

set updatetime=500

" move to beginning/end of line
nnoremap B ^
nnoremap E $

" Strip whitespace on save
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
let g:strip_whitespace_confirm=0

"turn on numbering
set nu

" set Vim-specific sequences for RGB colors
set t_Co=256
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors

colorscheme monokai
let g:monokai_term_italic = 1
let g:monokai_gui_italic = 1


au BufRead,BufNewFile *py,*pyw,*.c,*.h set tabstop=4

"spaces for indents
au BufRead,BufNewFile *.py,*pyw set shiftwidth=4
au BufRead,BufNewFile *.py,*.pyw set expandtab
au BufRead,BufNewFile *.py set softtabstop=4

" Use UNIX (\n) line endings.
au BufNewFile *.py,*.pyw,*.c,*.h set fileformat=unix

" Set the default file encoding to UTF-8:
set encoding=utf-8

" Keep indentation level from previous line:
autocmd FileType python set autoindent
autocmd FileType python set smartindent

set backspace=indent,eol,start

set splitbelow
set splitright

"YAPF automatically encodes PEP8 if leader-y is pressed
autocmd FileType python nnoremap <leader>y :0,$!yapf<Cr><C-o>

au BufNewFile *.py 0r ~/.vim/skeleton.py

"use space to open folds
nnoremap <space> za

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Vertical lines
let g:indentLine_char = '|'

" Undo tree
nnoremap <F3> :UndotreeToggle<cr>
if has("persistent_undo")
	set undodir=~/.undodir/
	set undofile
endif
let g:undotree_SetFocusWhenToggle = 1

nnoremap <leader>z Gzz

" Highlight 'self'
augroup python
    autocmd!
    autocmd FileType python
                \   syn keyword pythonSelf self
                \ | highlight def link pythonSelf Special
augroup end
```

**Comment by airblade** [comment] 2019-08-01 10:54
@georgelroberts Thanks for the extra information – it helps.

Do you still get this problem with `let g:kite_auto_complete=0`?

Do you still get this problem when you run Vim directly, i.e. not inside tmux?

By the way I have just realised the readme is slightly out of date regarding `completeopt`.  Kite will always update `completeopt` as follows every time you enter a Python buffer:

https://github.com/kiteco/vim-plugin/blob/9ac679d0f907674a57bee1167de03e7e15008739/autoload/kite.vim#L53-L54

The only difference it makes here is using `menuone` instead of `menu`.

**Comment by georgelroberts** [comment] 2019-08-02 14:08
Thanks for responding.

I don't get the problem with that added setting, however what is the expected usage in that case, eg <C-X><C-O> to get kite suggestions?

The behaviour doesn't seem to happen running vim outside tmux, however it normally works to start with inside tmux then errors start to appear after a bit of time.

Good to know about the config, thanks.

**Comment by airblade** [comment] 2019-08-02 15:07
You use `<C-X><C-U>` to get the completions.

Interesting to hear that errors only start to appear after some time – though it doesn't jog any ideas at the moment.

What does `:echo kite#utils#plugin_version()` give you?

**Comment by georgelroberts** [comment] 2019-08-02 15:29
Not sure if it helps, but it does appear to be worse when I have multiple tmux windows open...

1.0.36.

**Comment by jansorg** [comment] 2019-08-12 10:39
@georgelroberts Are you on macOS or Linux? Can you tell which version of tmux you're using?

**Comment by georgelroberts** [comment] 2019-08-12 10:55
Ubuntu 19.04 and tmux v2.8.

**Comment by airblade** [comment] 2019-08-14 09:41
@georgelroberts What shell are you using please?

After a bit of research it seems there are two categories of garbage characters in this kind of situation: ones that look like escape sequences (e.g. `[OC^`) and ones that look like repetitions of characters already in the buffer.

The former can be caused by a configuration mismatch between tmux and the terminal over something like the mouse.

The latter can relate to the redrawing of the screen when the content depends on the results of an asynchronous process (i.e. fetching completions).  I don't know how a screen redraw happens when tmux is involved; but perhaps vim wants to redraw the screen and the extra step with tmux opens a small window of time during which the arrival of completion results can muddle the redraw or keyboard input handling...  I don't really know.

**Comment by georgelroberts** [comment] 2019-08-15 13:33
I'm using bash. 

Interesting, I'll try removing everything from my tmux config and see if that helps.

**Comment by metalogical** [comment] 2019-08-30 17:30
@georgelroberts did you manage to resolve this issue?

I'm also seeing similar random character insertions. They seem to be repetitions of characters already in the buffer. I'm not convinced it's a redrawing issue, since the characters are actually insterted into the buffer -- maybe a keyboard input handling issue.

**Comment by airblade** [comment] 2019-08-31 12:54
@metalogical Are you using tmux too?

**Comment by metalogical** [comment] 2019-08-31 23:18
yep, I use tmux on macOS, since my terminal has no scrollback, tabs, etc.

**Comment by airblade** [comment] 2019-09-02 11:00
What does `echo &timeout &ttimeout &ttimeoutlen` produce?

**Comment by metalogical** [comment] 2019-09-05 15:57
`1 1 50`

**Comment by airblade** [comment] 2019-09-06 11:34
Thanks.  Does this help: `set ttimeoutlen=0`?

Or this in tmuxrc: `set -g escape-time 20`?

Both those are based on neovim/neovim#2903.

I still have no idea what the cause could be.  I'm confident the plugin isn't doing anything weird.  I presume the garbage characters are due to some interaction between tmux, the terminal, and (Neo)vim.

**Comment by airblade** [comment] 2019-09-06 14:16
Is `$TERM` inside your tmux `screen*` or `tmux*`?

(tmux/tmux#625)

**Comment by metalogical** [comment] 2019-09-10 23:07
`$TERM` is correct. I use `set -g escape-time 0` in `tmux.conf`, so it should not be intercepting any escapes. I will try `ttimeoutlen` and report back.

I'm fairly confident thought that it's not a problem at the painting level, as the extraneous characters really do end up in my nvim buffer, and are written to disk on save.

**Comment by airblade** [comment] 2019-09-11 07:49
I agree it's not a painting problem; I was just wondering whether character codes were being misinterpreted somewhere along the way, causing vim/neovim to think characters had been typed when they hadn't been.

**Comment by airblade** [comment] 2019-09-12 07:30
@metalogical Do you still get this problem with let g:kite_auto_complete=0?

**Comment by jansorg** [comment] 2019-09-18 14:06
@metalogical Could you provide an update?

**Comment by metalogical** [comment] 2019-09-18 16:41
I haven't been coding as much in Python recently, and haven't been able to reproduce this with artificial testing. I think it's safe to close this for now, and if I uncover more information, we can reopen.

**Closed by metalogical** 2019-09-18 16:41 UTC
Labels: bug
