### ISSUE TITLE
Fuzzy completion / not only to match from starting? 

### ISSUE THREAD

**Issue by hongyi-zhao** [kiteco/vim-plugin#253] opened 2020-01-16 12:23 UTC
Hi,

Say, for typing the following one:

`from __future__ `

If I type as the following:

`from fut<tab>`

Then kite will not list the results, but pycharm will do the trick.

So, could you please add the features to kite such as: Fuzzy completion / not only to match from starting? 

Regards

**Comment by airblade** [comment] 2021-01-28 11:27
@hongyi-zhao Sorry for the slow reply.  I'm not sure how we missed this!

@metalogical Kite must support this if Pycharm can do it.  Can you shed any light on how Pycharm does it?  If not I'll dig into Pycharm's code and try to figure it out.

**Comment by hongyi-zhao** [comment] 2021-01-28 13:29
To be frank, I've discarded Pycharm for a long time since I've posted this issue. I hope you can figure it out easily.

**Comment by metalogical** [comment] 2021-02-02 20:32
duplicate of https://github.com/kiteco/issue-tracker/issues/85

**Closed by metalogical** 2021-02-02 20:32 UTC
