### ISSUE TITLE
Kite is conflicting with auto-pairs vim-closer and basically anything that uses the Enter key

### ISSUE THREAD

**Issue by nschurmann** [kiteco/vim-plugin#313] opened 2020-11-12 03:12 UTC
I was using auto-pairs, however it stopped working properly after installing kite:

```javascript
const lala = () => {//cursor here}

// produces this:
const lala = () => {
//cursor here}

//instead of this
const lala = () => {
  //cursor here
}
```

Is there a work around for this?

**Comment by airblade** [comment] 2020-11-12 10:58
Does `let g:kite_deconflict_cr=1` fix this?

**Comment by airblade** [comment] 2020-11-12 16:08
Does this help?

```diff
diff --git i/autoload/kite.vim w/autoload/kite.vim
index 47a47e4..1f0ba02 100644
--- i/autoload/kite.vim
+++ w/autoload/kite.vim
@@ -154,24 +154,6 @@ endfunction
 
 
 function! s:setup_mappings()
-  " When the pop-up menu is closed with <C-e>, <C-y>, or <CR>,
-  " the TextChangedI event is fired again, which re-opens the
-  " pop-up menu.  To avoid this, we set a flag when one of those
-  " keys is pressed.
-  "
-  " Note the <CR> mapping can conflict with vim-endwise because vim-endwise
-  " also maps <CR>.  To work around the conflict:
-  "
-  "     let g:kite_deconflict_cr = 1
-  "
-  imap <buffer> <expr> <C-e> kite#completion#popup_exit("\<C-e>")
-  imap <buffer> <expr> <C-y> kite#completion#popup_exit("\<C-y>")
-  if exists('g:kite_deconflict_cr') && g:kite_deconflict_cr
-    imap <silent> <buffer> <CR> <C-R>=kite#completion#popup_exit('')<CR><CR>
-  else
-    imap <buffer> <expr> <CR> kite#completion#popup_exit("\<CR>")
-  endif
-
   if exists('g:kite_tab_complete')
     imap <buffer> <expr> <Tab> pumvisible() ? "\<C-y>" : "\<Tab>"
   endif
```

I can't seem to reproduce the problem that led me to add that code in the first place.

**Comment by airblade** [comment] 2020-11-12 16:12
Some links:

- [How vim-closer sets up its `<CR>` map](https://github.com/rstacruz/vim-closer/blob/c61667d27280df171a285b1274dd3cf04cbf78d4/autoload/closer.vim#L4-L25)
- [How vim-mucomplete minimises side-effects](https://github.com/lifepillar/vim-mucomplete/commit/8d2845baa187ac50b0da878b82e322d38e1859f4)
- [How auto-pairs sets up its `<CR>` map](https://github.com/jiangmiao/auto-pairs/blob/39f06b873a8449af8ff6a3eee716d3da14d63a76/plugin/auto-pairs.vim#L603-L670).

**Comment by nschurmann** [comment] 2020-11-13 01:12
@airblade it partially fix the problem, now I'm having another issue:

```javascript
const lala = () => {//cursor here}

// produces this:
const lala = () => {
//cursor here
}

//instead of this
const lala = () => {
  //cursor here
}
```
It's missing the tab. If I'm correct I think the script is doing a `ko`, and if I do that then I do get the correct indentation, just not when I'm just pressing Enter.

**Comment by airblade** [comment] 2020-11-13 10:19
I can't reproduce this.  I agree that's the key line in this case but for me the cursor is indented as expected.

Maybe you have another plugin or bit of configuration which is affecting this?

**Comment by airblade** [comment] 2020-12-04 15:34
I'm closing this because the original issue has been fixed.  Please feel free to open a new issue if you're still having problems with the indentation.  Thanks!

**Closed by airblade** 2020-12-04 15:34 UTC
