### ISSUE TITLE
User reported Kite crashed Vim

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#271] opened 2020-04-24 17:16 UTC
> When i held down the delete key in insert mode in chin it kept inserting suggested text

Will ask the user to provide his `.vimrc` setup. @airblade any other info necessary?

**Comment by ryx2** [comment] 2020-04-24 17:23
https://github.com/ryx2/rc/blob/master/vimrc

This is my vimrc. 

Vim didn't "crash" it just kept inserting the same suggested function when i held the delete key in insert mode, making it unusable

**Comment by ryx2** [comment] 2020-04-24 17:26
This is with vim8, vim-gtk

**Comment by airblade** [comment] 2020-04-28 12:37
@ryx2 Thanks for linking to your vimrc.  However it mostly sources other files which don't seem to be on GitHub, so it's hard to get a full picture of your vim setup.

Anyway, it would be great if you could please let me know:

- What was the function that kept being inserted?
- Did this start in the middle of a completion or just when typing without any completions?
- Can you reproduce it consistently?
- What is `:echo kite#utils#plugin_version()`?

**Comment by ryx2** [comment] 2020-05-01 07:05
Thanks for getting back to me!

I forgot to mension, this only happens when I'm using vim to edit python files. The function is "=AutoPairsDelete()". it does not occur when i have all my plugins commented out in my vimrc. I have included a screenshot of what the unwanted insert. I just typed out "asdfasdfasdfasdfasdfasdfasdf etc" and held backspace, with kite's vim plugin on, hitting enter a few times and doing this again.  

It appears to occur randomly, but only when deleting text, not when deleting blank spaces. It also inserts when it is deleting the function that it autoinserted. Also, if i carefully hit the delete button once at a time, the insert does not happen. If I hold it down, that's when the unwanted insert occurs. When I tried double tapping the delete button, i was able to recreate the problem.  

my vim kite version is 1.0.64

I am willing to collaborate as much as you want to help fix this. I love kite for pycharm, and would love it working for my vim too. 
![vim_unwanted_insert](https://user-images.githubusercontent.com/21298347/80788702-d7f82180-8b57-11ea-99d9-e8af60015c4b.png)

**Comment by airblade** [comment] 2020-05-01 09:06
Thanks for all the information, espcially the tip about vim-airline.  I'll investigate...

Note to self: looks like https://github.com/kiteco/vim-plugin/issues/214#issuecomment-558696474.

**Comment by airblade** [comment] 2020-05-01 09:30
Hmm, I can't reproduce this yet.

Does it happen when you have a minimal vimrc and your only plugins are this one, vim-airline, and auto-pairs?

What does `:imap` look like?

**Comment by airblade** [comment] 2020-05-01 11:07
Thinking out loud:

- The text `=AutoPairsDelete()` is inserted.
- That text comes from [here](https://github.com/jiangmiao/auto-pairs/blob/39f06b873a8449af8ff6a3eee716d3da14d63a76/plugin/auto-pairs.vim#L544-L545):

        " Use <C-R> instead of <expr> for issue #14 sometimes press BS output strange words
        execute 'inoremap <buffer> <silent> <BS> <C-R>=AutoPairsDelete()<CR>'

- `<C-R>=` means insert the result of evaluating the expression.
- We know the problem occurs with two rapid `<BS>`s.

**Comment by ryx2** [comment] 2020-05-02 05:31
Found something. I have my <C-c> in my vimrc. 

vnoremap <C-c> "+yy

When I comment this line out, I can have vim-airline, no problem. 

I use this along with vim-gtk to use ctrl-C to copy text from vim into my regular clipboard. I guess I could find another key (ctrl c was intuitive as the copy mechanism for the regular keyboard). But I dont want to find another way to copy text haha i loved the shift-V select block text ctrl-c copy it out of vim haha

**Comment by airblade** [comment] 2020-05-04 09:23
Sorry, that echo should have been:

```viml
:echo &timeout &ttimeout &timeoutlen &ttimeoutlen
```

Also, the `vnoremap` looks incomplete: it's missing the left hand side, I think?

**Comment by airblade** [comment] 2020-05-04 09:30
Does this fix the problem?

```diff
diff --git i/autoload/kite/snippet.vim w/autoload/kite/snippet.vim
index 51a2b6d..5f604b9 100644
--- i/autoload/kite/snippet.vim
+++ w/autoload/kite/snippet.vim
@@ -266,7 +266,6 @@ function! s:remove_smaps_for_printable_characters()
         \ '<C-Tab>',
         \ '<NL>',
         \ '<CR>',
-        \ '<BS>',
         \ '<Leader>',
         \ '<LocalLeader>'
         \ ]
```

**Comment by airblade** [comment] 2020-05-04 09:49
Does this help?

```diff
- vnoremap <C-c> "+yy
+ xnoremap <C-c> "+yy
```

**Comment by airblade** [comment] 2020-05-26 14:06
@ryx2 Have you been able to look at this?

**Comment by airblade** [comment] 2020-12-04 12:55
@ryx2 I'm going to close this because it has gone quiet, and also the plugin has changed quite a lot.  Please open a new issue if you have any further problems.  Thanks!

**Closed by airblade** 2020-12-04 12:55 UTC
Labels: bug
