### ISSUE TITLE
Slight autocomplete bug

### ISSUE THREAD

**Issue by TravisDart** [kiteco/vim-plugin#234] opened 2019-11-12 18:07 UTC
I was following `:KiteTutorial` and the autocomplete did not work quite as described.

I used a blank config, then ran `:KiteTutorial`

    $ touch ~/Desktop/blankconfig.txt
    $ nvim -u ~/Desktop/blankconfig.txt

The instructions say `Type "m", and Kite will suggest calling "dumps(<obj>, ensure_ascii=<bool>)".` However, I find I must type `mp` to get the snippet.

When I type `m` I get:
![Screen Shot 2019-11-12 at 11 10 32 AM 1](https://user-images.githubusercontent.com/5155310/68697492-870e5580-0544-11ea-9e72-fa6fdea20434.png)

Then when I type `p` I get the expected behavior:
![Screen Shot 2019-11-12 at 11 10 53 AM](https://user-images.githubusercontent.com/5155310/68697515-97263500-0544-11ea-885a-294f2f4a74e9.png)

Strangely, if I hit backspace twice and go back to the starting place, the autocomplete works as expected when I hit `m` again:
![Screen Shot 2019-11-12 at 11 11 04 AM](https://user-images.githubusercontent.com/5155310/68697619-d2c0ff00-0544-11ea-8141-6b13fc7350e5.png)

**Comment by jansorg** [comment] 2019-11-13 15:08
@metalogical Could you comment on this? afaik it's due to the time-bound nature of snippet completions

**Comment by metalogical** [comment] 2019-11-13 16:42
Kite starts to precompute "advanced" completions but doesn't necessarily wait on them to be fully computed before returning basic completions. It also has an internal cache, which is why when you backspace and retype, you see the call completions.

In this case, we *might* be able to block for longer for those call completions, since those are not actually that slow. We'll track this as a future improvement (but not a bug).

There's also potentially an issue with the tutorial file being misleading or confusing: @plungg @its-dhung 

Closing this since it's not a bug. We will incrementally improve performance details like this over time.

**Closed by metalogical** 2019-11-13 16:42 UTC
