### ISSUE TITLE
Vim plugin is changing the color scheme

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#189] opened 2019-06-14 17:07 UTC
@felixblind mentioned:

> When I use as `:!` command in vim, for example to run `:! python %` while kite is indexing the color scheme of my terminal (xterm) is scrambled up.

@felixblind do you mind sharing the contents of your `~/.vimrc` file?

**Comment by felixblind** [comment] 2019-06-14 19:06
`if &compatible
    set nocompatible "do not act like vi
endif
" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.vim/plugged')
Plug 'davidhalter/jedi-vim'
Plug 'ervandew/supertab'
" Plug 'Valloric/YouCompleteMe'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'raimondi/delimitmate'

" tmux integration
" Plug 'benmills/vimux'
" Plug 'christoomey/vim-tmux-navigator'
" dispatch allows for compiling / running code in another tmux window
" Plug 'tpope/vim-dispatch'
" Plug 'jpalardy/vim-slime'
Plug 'benmills/vimux'
" Plug 'julienr/vimux-pyutils'

" Ale is a asynchronous linter
Plug 'w0rp/ale'

Plug 'wakatime/vim-wakatime'

"" Colors 
" Plug 'flazz/vim-colorschemes'
Plug 'morhetz/gruvbox'


Plug 'leafgarland/typescript-vim'
Plug 'pangloss/vim-javascript'
Plug 'neovimhaskell/haskell-vim'
Plug 'jaspervdj/stylish-haskell'


" Initialize plugin system
call plug#end()
filetype plugin on "checks what file smt is

" matchit is a plugin which is shipped with vim, but not activated.
" Matchit enhances the functionality of the % command. When this plugin is
" enabled, the % command can jump between matching pairs of keywords.
runtime macros/matchit.vim

" setlocal tabstop=4
" setlocal softtabstop=4
" setlocal shiftwidth=4
" setlocal autoindent
setlocal fileformat=unix
"" vimscript the hard way
" easytags plugin: this just prevents highlighting for all file types. File
" types for which hightlighting should be enabled have to be whitelisted
" let b:easytags_auto_highlight = 0
" source ~/.vim/preferences/ycm.vim
" source ~/.vim/preferences/nerdtree.vim

source ~/.vim/preferences/ale.vim
source ~/.vim/preferences/statusline.vim
source ~/.vim/preferences/executive_settings.vim
source ~/.vim/preferences/jedi.vim
source ~/.vim/preferences/supertab.vim


"Folding
" set foldmethod=indent " Enable Folding
" set foldlevel=99
" " Enable folding with the space bar
" nnoremap <space> za
"" Save when losing focus
au FocusLost * :silent! wall




" restrict usage of some commands in non-default .vimrc files; commands that
" write to file or execute shell commands are not allowed and map commands are
" displayed.
set exrc
set secure

nnoremap <leader>vimrc :vsplit $MYVIMRC<cr> " quickly edit vimrc
nnoremap <leader>sv :source $MYVIMRC<cr> " quickly source vimrc

set nrformats=
set number
set relativenumber

if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  " see also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
  " let base16colorspace=256  " Access colors present in 256 colorspace
  " Allow color schemes to do bright colors without forcing bold.
  set t_Co=256
  " colorscheme desert
  " colorscheme Tomorrow-Night
  colorscheme gruvbox
  let g:gruvbox_undercurl = 1
  let g:gruvbox_termcolors = 256
  let g:gruvbox_constrast_dark='soft'
  let g:gruvbox_underline=1
  " let g:gruvbox_color_column='red'
  
  set background=dark
endif

set encoding=utf-8
set expandtab

set noerrorbells

syntax on
filetype indent plugin on

"Brackets
let delimitMate_expand_cr = 0
"
" turn off search highlight
nnoremap <silent> <leader><space> :nohlsearch<CR>

let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"


" set clipboard=unnamedplus

" searching
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set smartcase

set formatoptions+=j " Delete comment character when joining commented lines

set noshowmode
set showcmd
set title

set wildmenu  " visual autocomplete for command menu behaviour like in bash
set wildmode=longest,list
set autoread
set history=200
set backspace=

set nobackup
set noswapfile
" set backupdir=~/.vim_backup//
" set directory=~/Dropbox/.vim/swap//

" by default <c-p> and <c-n> do not filter the the command history
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
cnoremap <Up> <nop>
cnoremap <Down> <nop>
nnoremap <F1> <nop> " F1 triggers the help
nnoremap Q <nop> " Q starts ex mode
"nnoremap K <nop> " brings up man page

set shortmess+=I " omits the starting message
" nnoremap Y y$ 

set splitbelow
set splitright

"set cursor
" let NVIM_TUI_ENABLE_CURSOR_SHAP=1

" gvim part
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right Scrollbar
set winaltkeys=menu

" Time out on key codes but not mappings.
" Basically this makes terminal Vim work sanely.
set notimeout
set ttimeout
set ttimeoutlen=10


" Make sure Vim returns to the same line when you reopen a file.
augroup line_return
  au!
  au BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \     execute 'normal! g`"zvzz' |
        \ endif
augroup END

" allows buffers not to be saved when changing them
set hidden
" nnoremap <silent> [b :w<cr>:bprevious<cr>
" nnoremap <silent> ]b :w<cr>:bnext<cr>
" nnoremap <silent> [P :w<cr>:bfirst<cr>
" nnoremap <silent> ]P :w<cr>:blast<cr>
" Remember: if vim automatically saves when you switch a tab then there is no
" way back when editing to buffers at once.
nnoremap <silent> [b :bprevious<cr>
nnoremap <silent> ]b :bnext<cr>
nnoremap <silent> [P :bfirst<cr>
nnoremap <silent> ]P :blast<cr>

" ctags - automatic tags generation
:autocmd BufWritePost * call system("ctags -R --exclude=static --exclude=.git --languages=-sql --exclude=plugged")

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

set clipboard+=unnamedplus

nnoremap <silent> [x :w<cr>:bdelete<cr>
nnoremap <silent> [q :bdelete<cr>

" set completeopt=longest,menuone
`
I can also give you what's in the sourced files but the color specs are here.

**Comment by airblade** [comment] 2019-06-17 14:45
I can't think why the Kite plugin would be scrambling your colours.  When the statusline says "Kite: indexing", Vim isn't doing anything in particular; the Kite helper process is running in its own process.

The plugin simply polls a status endpoint every 5s and updates the statusline with the result, e.g. "indexing", "ready", etc.  From Vim's point of view there isn't anything special about the indexing state.

I wonder whether it's to do with the Kite status changing from indexing to ready, at the same time as you run a program via `:!` which updates the status line area.  Perhaps Vim has some kind of bug updating the status line area when there's a race between a background timer and a foreground process.

I can't reproduce the problem which makes debugging tricky.  Ideally I'd start with an empty/default vimrc, and no other plugins, and add your configuration back in a little at a time until the problem started to appear.  But that might take a while and you probably don't want to do that!

**Comment by airblade** [comment] 2020-12-04 12:11
The plugin has had a number of improvements in the past 18 months to prevent the screen getting garbled.  I'm going to close this now but please do open a new issue if you have any further problems.  Thanks!

**Closed by airblade** 2020-12-04 12:11 UTC
Labels: bug
