### ISSUE TITLE
vim throws error on start when opening with `vim -S Session.vim`

### ISSUE THREAD

**Issue by F3R70** [kiteco/vim-plugin#294] opened 2020-08-05 13:09 UTC
```
"temp.md" 439L, 15458C
Error detected while processing function kite#utils#kite_running:
line   10:
E117: Unknown function: kite#async#sync
Press ENTER or type command to continue
```

```
Error detected while processing function kite#utils#kite_running:
line   10:
E116: Invalid arguments for function split(kite#async#sync(cmd), '\n'), process) > -1
 ```

```
Error detected while processing function kite#utils#kite_running:
line   10:
E116: Invalid arguments for function split(kite#async#sync(cmd), '\n'), process) > -1
Press ENTER or type command to continue
Error detected while processing function kite#utils#kite_running:
line   10:
E116: Invalid arguments for function match(split(kite#async#sync(cmd), '\n'), process) > -1

```

**Comment by airblade** [comment] 2020-08-05 13:27
How did you produce your Session.vim file?

**Comment by FernandoTorres** [comment] 2020-08-05 18:15
I created it with

```
:mksession
```

I also tried replicating the issue in other project and it throws no error ... however the problem persist with the first Session.vim file.

PS: I deleted and re-created the Session.vim file and now it works with no error msgs

**Comment by airblade** [comment] 2020-08-06 10:38
I'm not sure exactly what the problem is but I suspect session files can get out of step when you install / uninstall a plugin between making and loading a session.  Perhaps that happened here?

Having said that, with `vim -S Session.vim` plugins should be loaded by the time the session file is read so I don't know why vim couldn't find `kite#async#sync()`.

I would hope that this is a one-off problem and it won't happen again.

**Comment by airblade** [comment] 2020-12-04 15:31
I'm closing this because the problem seems to be resolved.  Please open a new issue if it comes up again.  Thanks!

**Closed by airblade** 2020-12-04 15:31 UTC
